WITH MYTABLE AS
(SELECT EMPLOYEE.ID AS ID,
    EMPLOYEE.NAME AS NAME,
    EMPLOYEE.SALARY AS SALARY,
    EMPLOYEE.DEPARTMENTID AS DEPARTMENTID,
    DEPARTMENT.ID AS DID,
    DEPARTMENT.NAME AS DNAME,
    RANK() OVER (PARTITION BY DEPARTMENT.NAME ORDER BY EMPLOYEE.SALARY desc) AS ERANK
FROM EMPLOYEE INNER JOIN DEPARTMENT
ON EMPLOYEE.DEPARTMENTID = DEPARTMENT.ID
)

SELECT DNAME AS DEPARTMENT, NAME AS EMPLOYEE, SALARY
FROM MYTABLE
WHERE ERANK= 1;