
WITH EMPLOYEE(EMPLOYEE_ID) AS(
SELECT EMPLOYEE_ID FROM EMPLOYEES
UNION 
SELECT EMPLOYEE_ID FROM SALARIES
)

SELECT EMPLOYEE_ID FROM EMPLOYEE
WHERE EMPLOYEE_ID NOT IN 
(SELECT EMPLOYEE_ID FROM EMPLOYEES)

UNION

SELECT EMPLOYEE_ID FROM EMPLOYEE
WHERE EMPLOYEE_ID NOT IN 
(SELECT EMPLOYEE_ID FROM SALARIES)

ORDER BY EMPLOYEE_ID;