SELECT NAME FROM
SALESPERSON WHERE NAME NOT IN(
SELECT SALESPERSON.NAME AS NAME
FROM SALESPERSON INNER JOIN ORDERS
ON SALESPERSON.SALES_ID = ORDERS.SALES_ID
INNER JOIN COMPANY
ON COMPANY.COM_ID = ORDERS.COM_ID
WHERE COMPANY.NAME = 'RED');