WITH MYORDER AS
(
    SELECT *
    FROM ORDERS
    WHERE YEAR(ORDER_DATE) = '2019'
)

SELECT U.USER_ID AS buyer_id, U.JOIN_DATE AS join_date, COUNT(M.BUYER_ID) AS orders_in_2019
FROM USERS U LEFT JOIN MYORDER M
ON U.USER_ID = M.BUYER_ID
GROUP BY U.USER_ID