WITH USER AS (
    SELECT USERS_ID
    FROM USERS 
    WHERE BANNED = 'NO'
),
TRIP AS (
    SELECT ID, CLIENT_ID, DRIVER_ID, CITY_ID, STATUS, REQUEST_AT
    FROM TRIPS
    WHERE REQUEST_AT >= "2013-10-01" AND REQUEST_AT <= "2013-10-03"
)

SELECT REQUEST_AT AS Day,
ROUND(SUM(IF(STATUS <> 'completed', 1, 0))/COUNT(*), 2) AS 'Cancellation Rate'
FROM TRIP
WHERE CLIENT_ID IN (
    SELECT USERS_ID FROM USER
) AND
DRIVER_ID IN (
    SELECT USERS_ID FROM USER
)GROUP BY DAY